### PR TITLE
documented the --deleteme option

### PR DESCRIPTION
**Pull request by mgafner**
i was searching for an option to log out (to update the local cached tv channel list). after looking through the source code i found the undocumented --deleteme option. i updated the --help documentation and the man page.

### CODE REVIEW

**Comment by reduzent** [comment]
`--deleteme` actually does a different thing. It removes entries from the user's crontab. When configuring a recording for a future time, watchteleboy adds an entry to the user's crontab that deletes itself when executed by using the `--deleteme` flag, so that your crontab doesn't get polluted over time with stale entries.

But I think you have a valid point in that it might be desirable to purge caches. Actually, it does so already now, but only after the cookie expires (I believe). Maybe you can turn your pull request into a feature request.

**Comment by mgafner** [comment]
ok, i might change the pull request and add something like an option to --logout or --purge or --update-channel-list

what you think about it?

**Comment by reduzent** [comment]
Sounds good to me, probably --purge-caches | --pc... not sure.. but yes, i'd welcome such a feature

Right now watchteleboy seems broken. Something changed in their website and the TELEBOY_USER_ID can't be extracted. Getting the USER_ID is actually the weakest part as it does not rely on the API, but extracts it from some webpage (that is apparently prone to change).

**Comment by reduzent** [comment]
The current version is a rewrite from the ground up in Python. The merge request doesn't apply anymore

**Pull request closed without merging**
